name: frontend_ramdet
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Menyesuaikan lints yang aman untuk standar SDK Dart 3.10.x
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Catatan: Jika kedepannya ingin menambahkan aset gambar logo buatan sendiri 
  # untuk dipasang pada SplashScreen atau LoginScreen, silakan aktifkan bagian di bawah ini:
  # assets:
    - assets/images/